### ISSUE TITLE
[Quest/Malawi Core] Android App : Remove fetch userinfo step on login steps

### ISSUE THREAD

**Issue by sevenreup** [d-tree-org/fhircore#31]
The current login steps are

```mermaid
flowchart LR
    Token --> UserInfo --> practitioner-details
```

The data retrieved from `UserInfo` is the same data that we can retrieve by decoding the `JWT` token.

[practitioner-details response](https://github.com/d-tree-org/fhircore/files/14449134/tmp.json)
[UserInfo response](https://github.com/d-tree-org/fhircore/files/14449145/tmp.json)

## Proposal

Remove the UserInfo step and just decode the JWT data

**Comment by sevenreup** [comment]
@calmwalija @evance-mose  @KhumboLihonga  @LZRS Please look at this proposal and see if there is anything to consider

**Comment by calmwalija** [comment]
@sevenreup that's a good idea, the CHWs were also complaining about how slow it is logging in, I can look into it!

**Comment by sevenreup** [comment]
And another step we can take is right now.

The only time we skip sending a request to the server at login is when there is no network. But we can also just check if the auth token is still active (and verify credintials) then just proceed to login instead of fetching the **practitioner-details** again. This will improve the login time at places with slower internet connectivity

**Comment by LZRS** [comment]
Yeah, I'm also in agreement since it would essentially simplify the process of login in the app

**Comment by KhumboLihonga** [comment]
This sounds like a good enhancement. What would be the level of effort on this? @sevenreup
